[2025-04-30T02:42:57.350+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clima_pluviometro_precipitacao_30min.transformar_dados scheduled__2025-04-30T02:00:00+00:00 [queued]>
[2025-04-30T02:42:57.356+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clima_pluviometro_precipitacao_30min.transformar_dados scheduled__2025-04-30T02:00:00+00:00 [queued]>
[2025-04-30T02:42:57.356+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-30T02:42:57.365+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transformar_dados> on 2025-04-30 02:00:00+00:00
[2025-04-30T02:42:57.368+0000] {standard_task_runner.py:60} INFO - Started process 277 to run task
[2025-04-30T02:42:57.371+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'clima_pluviometro_precipitacao_30min', 'transformar_dados', 'scheduled__2025-04-30T02:00:00+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/clima_pluviometro.py', '--cfg-path', '/tmp/tmpoygz5t43']
[2025-04-30T02:42:57.373+0000] {standard_task_runner.py:88} INFO - Job 196: Subtask transformar_dados
[2025-04-30T02:42:57.415+0000] {task_command.py:423} INFO - Running <TaskInstance: clima_pluviometro_precipitacao_30min.transformar_dados scheduled__2025-04-30T02:00:00+00:00 [running]> on host 3c8b9e914942
[2025-04-30T02:42:57.480+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='clima_pluviometro_precipitacao_30min' AIRFLOW_CTX_TASK_ID='transformar_dados' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-30T02:00:00+00:00'
[2025-04-30T02:42:57.482+0000] {logging_mixin.py:188} INFO - [clima_pluviometro.precipitacao_30min] Processando: data/landing/clima_pluviometro/precipitacao_30min/ano=2025/mes=04/dia=30/precipitacao_30min_20250430_024255.json
[2025-04-30T02:42:59.153+0000] {logging_mixin.py:188} INFO - [clima_pluviometro.precipitacao_30min] Parquet salvo em: data/bronze/clima_pluviometro/precipitacao_30min/ano=2025/mes=04/dia=30/precipitacao_30min_20250430_024257.parquet
[2025-04-30T02:42:59.154+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl/transform.py", line 62, in transformar_json_para_parquet
    os.remove(caminho_json)
FileNotFoundError: [Errno 2] No such file or directory: 'data/landing/clima_pluviometro/precipitacao_30min/ano=2025/mes=04/dia=30/precipitacao_30min_20250430_024255.json'
[2025-04-30T02:42:59.161+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=clima_pluviometro_precipitacao_30min, task_id=transformar_dados, execution_date=20250430T020000, start_date=20250430T024257, end_date=20250430T024259
[2025-04-30T02:42:59.172+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 196 for task transformar_dados ([Errno 2] No such file or directory: 'data/landing/clima_pluviometro/precipitacao_30min/ano=2025/mes=04/dia=30/precipitacao_30min_20250430_024255.json'; 277)
[2025-04-30T02:42:59.202+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-30T02:42:59.225+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
