[2025-04-30T12:16:06.386+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clima_pluviometro_precipitacao_30min.transformar_dados scheduled__2025-04-30T04:00:00+00:00 [queued]>
[2025-04-30T12:16:06.391+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clima_pluviometro_precipitacao_30min.transformar_dados scheduled__2025-04-30T04:00:00+00:00 [queued]>
[2025-04-30T12:16:06.392+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-30T12:16:06.400+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transformar_dados> on 2025-04-30 04:00:00+00:00
[2025-04-30T12:16:06.402+0000] {standard_task_runner.py:60} INFO - Started process 216 to run task
[2025-04-30T12:16:06.404+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'clima_pluviometro_precipitacao_30min', 'transformar_dados', 'scheduled__2025-04-30T04:00:00+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/clima_pluviometro.py', '--cfg-path', '/tmp/tmp_jq56yrh']
[2025-04-30T12:16:06.406+0000] {standard_task_runner.py:88} INFO - Job 211: Subtask transformar_dados
[2025-04-30T12:16:06.441+0000] {task_command.py:423} INFO - Running <TaskInstance: clima_pluviometro_precipitacao_30min.transformar_dados scheduled__2025-04-30T04:00:00+00:00 [running]> on host 307e8fe339ca
[2025-04-30T12:16:06.501+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='clima_pluviometro_precipitacao_30min' AIRFLOW_CTX_TASK_ID='transformar_dados' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-30T04:00:00+00:00'
[2025-04-30T12:16:06.502+0000] {logging_mixin.py:188} INFO - [clima_pluviometro.precipitacao_30min] Processando: data/landing/clima_pluviometro/precipitacao_30min/ano=2025/mes=04/dia=30/precipitacao_30min_20250430_121604.json
[2025-04-30T12:16:08.426+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl/transform.py", line 57, in transformar_json_para_parquet
    con.execute(f"COPY temp TO '{caminho_parquet}' (FORMAT 'parquet')")
duckdb.duckdb.IOException: IO Error: Could not set lock on file "data/bronze/clima_pluviometro/precipitacao_30min/ano=2025/mes=04/dia=30/precipitacao_30min_20250430_121606.parquet": Conflicting lock is held in /usr/local/bin/python3.8 (PID 217). See also https://duckdb.org/docs/connect/concurrency
[2025-04-30T12:16:08.432+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=clima_pluviometro_precipitacao_30min, task_id=transformar_dados, execution_date=20250430T040000, start_date=20250430T121606, end_date=20250430T121608
[2025-04-30T12:16:08.441+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 211 for task transformar_dados (IO Error: Could not set lock on file "data/bronze/clima_pluviometro/precipitacao_30min/ano=2025/mes=04/dia=30/precipitacao_30min_20250430_121606.parquet": Conflicting lock is held in /usr/local/bin/python3.8 (PID 217). See also https://duckdb.org/docs/connect/concurrency; 216)
[2025-04-30T12:16:08.461+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-30T12:16:08.477+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
