[2025-04-30T13:24:03.004+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: adm_cor_comando_ocorrencias.extrair_dados_ocorrencias manual__2025-04-30T13:24:01.843869+00:00 [queued]>
[2025-04-30T13:24:03.009+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: adm_cor_comando_ocorrencias.extrair_dados_ocorrencias manual__2025-04-30T13:24:01.843869+00:00 [queued]>
[2025-04-30T13:24:03.009+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-30T13:24:03.018+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extrair_dados_ocorrencias> on 2025-04-30 13:24:01.843869+00:00
[2025-04-30T13:24:03.021+0000] {standard_task_runner.py:60} INFO - Started process 241 to run task
[2025-04-30T13:24:03.023+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'adm_cor_comando_ocorrencias', 'extrair_dados_ocorrencias', 'manual__2025-04-30T13:24:01.843869+00:00', '--job-id', '235', '--raw', '--subdir', 'DAGS_FOLDER/adm_cor_comando.py', '--cfg-path', '/tmp/tmpbeh2beud']
[2025-04-30T13:24:03.024+0000] {standard_task_runner.py:88} INFO - Job 235: Subtask extrair_dados_ocorrencias
[2025-04-30T13:24:03.060+0000] {task_command.py:423} INFO - Running <TaskInstance: adm_cor_comando_ocorrencias.extrair_dados_ocorrencias manual__2025-04-30T13:24:01.843869+00:00 [running]> on host 81c910e0b178
[2025-04-30T13:24:03.122+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='adm_cor_comando_ocorrencias' AIRFLOW_CTX_TASK_ID='extrair_dados_ocorrencias' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T13:24:01.843869+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T13:24:01.843869+00:00'
[2025-04-30T13:24:03.124+0000] {logging_mixin.py:188} INFO - Extraindo dados da URL: https://api.dados.rio/v2/adm_cor_comando/ocorrencias/
[2025-04-30T13:24:03.754+0000] {logging_mixin.py:188} INFO - [ERRO] Falha na extração: 400 Client Error: Bad Request for url: https://api.dados.rio/v2/adm_cor_comando/ocorrencias/
[2025-04-30T13:24:03.755+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-30T13:24:03.762+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=adm_cor_comando_ocorrencias, task_id=extrair_dados_ocorrencias, execution_date=20250430T132401, start_date=20250430T132403, end_date=20250430T132403
[2025-04-30T13:24:03.796+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-30T13:24:03.812+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
